"""
This is a setup.py script generated by py2applet

Usage:
    py2applet --make-setup videodownloader.py
    python setup.py py2app -A --emulate-shell-environment
"""

from setuptools import setup

APP = ['videodownloader.py']
DATA_FILES = []
OPTIONS = {
    'iconfile': 'videodownloadericon.icns',
    'plist': {'CFBundleShortVersionString': '0.1.0', },
    'packages': ['youtube_dl']
}

setup(
    name="VideoDownloader",
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
